name = "Amethyst Smp"
author = "jvdsat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "008c494bc760cf8ccca1625b352c3c48b3230229202f94f0264f657a70db4c90"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
