name = "Amethyst Smp"
author = "jvdsat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ad156f6e784c968f70978812e7cdf72e0604f6bf1c157a1151c3789cb3ff74d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
