name = "Amethyst Smp"
author = "jvdsat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c101ed3a016d555900c9f3f5729a9893d6c6ac2837a1944b5de60ef1e487752f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
