name = "Amethyst Smp"
author = "jvdsat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b78b949dd95b5a27ed84f1bca1163208ae606ec59abbafcd9bef2613a46e282"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
