name = "Amethyst Smp"
author = "jvdsat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24f64fb1babc5efaa302be8bd2f00f33d38d2ec0bb50ad95ba8ade9024b30d94"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
